metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

metricbeat.modules:
  - module: vsphere
    enabled: true
    metricsets: ['datastore', 'host', 'virtualmachine']
    period: 1m
    hosts: ['${VCSA_URL}']

    username: '${VCSA_USERNAME}'
    password: '${VCSA_PASSWORD}'
    # If insecure is true, don't verify the server's certificate chain
    insecure: false

    # Get custom fields when using virtualmachine metric set. Default false.
    # get_custom_fields: false
  - module: docker
    metricsets:
      - container
      - cpu
      #  - diskio
      #  - event
      - healthcheck
    #  - info
    #  - memory
    #  - network
    period: 10s
    hosts: ['unix:///var/run/docker.sock']

output.elasticsearch:
  hosts: 'elasticsearch:9200'
#  pipeline: geoip-info

setup.template.overwrite: true

setup.kibana:
  host: 'kibana:5601'

xpack.monitoring.enabled: true
